version: '3'
services:
  server:
    build: server
    container_name: flaskr_server
    command: poetry run python -m flask run --host=0.0.0.0 --port=8000
    volumes:
      - ./server:/home/python/server
    environment:
      - FLASK_APP=main.py:app
      - FLASK_ENV=development
    ports:
      - 8000:8000
